//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CordovaResourceGenerator.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CordovaResourceGenerator.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid density: &apos;{0}&apos;..
        /// </summary>
        internal static string AndroidService_ConvertAndroidDensityToSize_InvalidDensity {
            get {
                return ResourceManager.GetString("AndroidService_ConvertAndroidDensityToSize_InvalidDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid orientation: &apos;{0}&apos;..
        /// </summary>
        internal static string AndroidService_ConvertAndroidDensityToSize_InvalidOrientation {
            get {
                return ResourceManager.GetString("AndroidService_ConvertAndroidDensityToSize_InvalidOrientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cordova project xml file has a icon or splash with a invalid height..
        /// </summary>
        internal static string CordovaProjectService_ExtractIconAndSplash_InvalidHeight {
            get {
                return ResourceManager.GetString("CordovaProjectService_ExtractIconAndSplash_InvalidHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cordova project xml file has a icon or splash with a invalid width..
        /// </summary>
        internal static string CordovaProjectService_ExtractIconAndSplash_InvalidWidth {
            get {
                return ResourceManager.GetString("CordovaProjectService_ExtractIconAndSplash_InvalidWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cordova project xml file has a icon or splash without a source attribute..
        /// </summary>
        internal static string CordovaProjectService_ExtractIconAndSplash_NotFoundIconOrSplashSource {
            get {
                return ResourceManager.GetString("CordovaProjectService_ExtractIconAndSplash_NotFoundIconOrSplashSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The density &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string CordovaProjectService_ExtractPlatform_DensityNotValid {
            get {
                return ResourceManager.GetString("CordovaProjectService_ExtractPlatform_DensityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected configuration has a nameless platform..
        /// </summary>
        internal static string CordovaProjectService_ExtractPlatform_PlatformNameNotFound {
            get {
                return ResourceManager.GetString("CordovaProjectService_ExtractPlatform_PlatformNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; doesn&apos;t exists..
        /// </summary>
        internal static string CordovaProjectService_ExtractPlatforms_FileNotFound {
            get {
                return ResourceManager.GetString("CordovaProjectService_ExtractPlatforms_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No platform specified for generation..
        /// </summary>
        internal static string ImageGenerationService_GenerateIconsAndSplashs_EmptyPlatforms {
            get {
                return ResourceManager.GetString("ImageGenerationService_GenerateIconsAndSplashs_EmptyPlatforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; doesn&apos;t exists..
        /// </summary>
        internal static string ImageGenerationService_GenerateIconsAndSplashs_FileNotFound {
            get {
                return ResourceManager.GetString("ImageGenerationService_GenerateIconsAndSplashs_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory &apos;{0} doesn&apos;t exists..
        /// </summary>
        internal static string ImageGenerationService_GenerateIconsAndSplashs_OutputNotFound {
            get {
                return ResourceManager.GetString("ImageGenerationService_GenerateIconsAndSplashs_OutputNotFound", resourceCulture);
            }
        }
    }
}
