//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CordovaResourceGenerator.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CordovaResourceGenerator.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icons and splashs was generated successfully..
        /// </summary>
        public static string FinishedWizardPage_Description {
            get {
                return ResourceManager.GetString("FinishedWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to open the output folder..
        /// </summary>
        public static string FinishedWizardPage_Hyperlink_Text {
            get {
                return ResourceManager.GetString("FinishedWizardPage_Hyperlink_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string FinishedWizardPage_Title {
            get {
                return ResourceManager.GetString("FinishedWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This guide will help you through the process of generating icons and splashs for a cordova project..
        /// </summary>
        public static string IntroductionWizardPage_Description {
            get {
                return ResourceManager.GetString("IntroductionWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordova Icon &amp; Splash Generator.
        /// </summary>
        public static string IntroductionWizardPage_Title {
            get {
                return ResourceManager.GetString("IntroductionWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid page type..
        /// </summary>
        public static string PageFactory_PageTypeInvalid {
            get {
                return ResourceManager.GetString("PageFactory_PageTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the background color of the final icons and splashs (leave blank for transparent):.
        /// </summary>
        public static string SelectColorAndOutputWizardPage_Color_Description {
            get {
                return ResourceManager.GetString("SelectColorAndOutputWizardPage_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Color.
        /// </summary>
        public static string SelectColorAndOutputWizardPage_ColorDialog_Title {
            get {
                return ResourceManager.GetString("SelectColorAndOutputWizardPage_ColorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder.
        /// </summary>
        public static string SelectColorAndOutputWizardPage_OutputFolder_Button {
            get {
                return ResourceManager.GetString("SelectColorAndOutputWizardPage_OutputFolder_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an output folder to the icons and splashs:.
        /// </summary>
        public static string SelectColorAndOutputWizardPage_OutputFolder_Description {
            get {
                return ResourceManager.GetString("SelectColorAndOutputWizardPage_OutputFolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Background color &amp; Output folder.
        /// </summary>
        public static string SelectColorAndOutputWizardPage_Title {
            get {
                return ResourceManager.GetString("SelectColorAndOutputWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectConfigWizardPage_Button_Label {
            get {
                return ResourceManager.GetString("SelectConfigWizardPage_Button_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the config.xml file from the chosen cordova project:.
        /// </summary>
        public static string SelectConfigWizardPage_Description {
            get {
                return ResourceManager.GetString("SelectConfigWizardPage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Cordova Configuration File.
        /// </summary>
        public static string SelectConfigWizardPage_FileDialog_Filter {
            get {
                return ResourceManager.GetString("SelectConfigWizardPage_FileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordova Project.
        /// </summary>
        public static string SelectConfigWizardPage_Title {
            get {
                return ResourceManager.GetString("SelectConfigWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image File.
        /// </summary>
        public static string SelectImagesWizardPage_FileDialog_Filter {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_FileDialog_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source Icon.
        /// </summary>
        public static string SelectImagesWizardPage_FileDialogIcon_Button {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_FileDialogIcon_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source icon image.
        /// </summary>
        public static string SelectImagesWizardPage_FileDialogIcon_Title {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_FileDialogIcon_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Source Splash.
        /// </summary>
        public static string SelectImagesWizardPage_FileDialogSplash_Button {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_FileDialogSplash_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the source splash image.
        /// </summary>
        public static string SelectImagesWizardPage_FileDialogSplash_Title {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_FileDialogSplash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You only selected the icon image source. By doing this the icon will be used to generate the final splashs images..
        /// </summary>
        public static string SelectImagesWizardPage_OnlyIconSelected_MessagBox_Message {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_OnlyIconSelected_MessagBox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string SelectImagesWizardPage_OnlyIconSelected_MessagBox_Title {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_OnlyIconSelected_MessagBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Icon &amp; Splash.
        /// </summary>
        public static string SelectImagesWizardPage_Title {
            get {
                return ResourceManager.GetString("SelectImagesWizardPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string WizardWindow_Button_Cancel {
            get {
                return ResourceManager.GetString("WizardWindow_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt; Next.
        /// </summary>
        public static string WizardWindow_Button_Next {
            get {
                return ResourceManager.GetString("WizardWindow_Button_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous &gt;.
        /// </summary>
        public static string WizardWindow_Button_Previous {
            get {
                return ResourceManager.GetString("WizardWindow_Button_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error ocurred on the generation: {0}.
        /// </summary>
        public static string WizardWindow_Generate_Error_Description {
            get {
                return ResourceManager.GetString("WizardWindow_Generate_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string WizardWindow_Generate_Error_Title {
            get {
                return ResourceManager.GetString("WizardWindow_Generate_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cordova Icon &amp; Splash Generator.
        /// </summary>
        public static string WizardWindow_Title {
            get {
                return ResourceManager.GetString("WizardWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string WizardWindow_UnknownError {
            get {
                return ResourceManager.GetString("WizardWindow_UnknownError", resourceCulture);
            }
        }
    }
}
